# 이탈리아 여행 회화 150선
# 동선: 로마 입국 → 피렌체 → 베네치아 → 밀라노 → 돌로미티 → 시칠리아 → 로마 아웃
# 각 표현: short_en/short_it(실전 단답) + en/it(풀 문장) + q(상대방 질문, 해당 시)

PHRASES = [

    # ===== 1-12: 로마 공항 · 입국 · 숙소 =====
    {
        "no": 1,
        "category": "✈️ 로마 공항 · 입국",
        "situation": "입국 심사대에서 여권 제출",
        "q": "May I see your passport? / Posso vedere il suo passaporto?",
        "short_en": "Here.",
        "short_it": "Ecco.",
        "en": "Here is my passport.",
        "it": "Ecco il mio passaporto.",
        "pron": "에꼬 일 미오 파사포르토",
        "tip": "💡 여권을 내밀며 'Here.' 한 마디면 충분! 풀 문장은 더 정중한 표현이에요."
    },
    {
        "no": 2,
        "category": "✈️ 로마 공항 · 입국",
        "situation": "입국 심사 - 방문 목적",
        "q": "What is the purpose of your visit? / Qual è il motivo della sua visita?",
        "short_en": "Tourism. / Holiday.",
        "short_it": "Turismo.",
        "en": "I'm here for tourism.",
        "it": "Sono qui per turismo.",
        "pron": "소노 쿠이 페르 투리스모",
        "tip": "💡 실제로는 'Tourism.' 한 단어로 99% 해결! 더 설명이 필요할 때만 풀 문장을 써요."
    },
    {
        "no": 3,
        "category": "✈️ 로마 공항 · 입국",
        "situation": "입국 심사 - 체류 기간",
        "q": "How long will you be staying? / Quanto tempo si fermerà?",
        "short_en": "Three weeks. / Two weeks.",
        "short_it": "Tre settimane. / Due settimane.",
        "en": "I'll stay for three weeks.",
        "it": "Mi fermo per tre settimane.",
        "pron": "미 페르모 페르 트레 세티마네",
        "tip": "💡 숫자만 바꾸면 OK: una settimana(1주), due(2주), tre(3주), un mese(한 달)"
    },
    {
        "no": 4,
        "category": "✈️ 로마 공항 · 입국",
        "situation": "입국 심사 - 숙소 주소",
        "q": "Where are you staying? / Dove alloggerà?",
        "short_en": "[Hotel name], Rome.",
        "short_it": "All'hotel [nome], Roma.",
        "en": "I'm staying at [hotel name] in Rome.",
        "it": "Alloggio all'hotel [nome] a Roma.",
        "pron": "알로조 알로텔 [이름] 아 로마",
        "tip": "💡 호텔 예약확인서를 미리 꺼내두면 주소를 보여주는 것만으로도 끝나요!"
    },
    {
        "no": 5,
        "category": "✈️ 로마 공항 · 짐",
        "situation": "수하물 찾는 곳 물을 때",
        "short_en": "Baggage claim?",
        "short_it": "Ritiro bagagli?",
        "en": "Where is the baggage claim?",
        "it": "Dov'è il ritiro bagagli?",
        "pron": "도베 일 리티로 바갈리",
        "tip": "💡 공항 표지판에 'Ritiro Bagagli'라고 적혀 있어요. 표지판만 따라가도 OK!"
    },
    {
        "no": 6,
        "category": "✈️ 로마 공항 · 짐",
        "situation": "짐이 도착하지 않았을 때",
        "short_en": "My bag is missing!",
        "short_it": "Il mio bagaglio è perso!",
        "en": "My luggage is missing. Who can I report this to?",
        "it": "Il mio bagaglio è andato perso. A chi devo rivolgermi?",
        "pron": "일 미오 바갈리오 에 안다토 페르소. 아 키 데보 리볼제르미",
        "tip": "💡 분실 즉시 항공사 카운터(sportello)로! 신고서(PIR) 받아두면 보상 청구 가능해요."
    },
    {
        "no": 7,
        "category": "✈️ 로마 공항 · 이동",
        "situation": "공식 택시 타는 곳 물을 때",
        "short_en": "Official taxi?",
        "short_it": "Taxi ufficiale?",
        "en": "Where can I get an official taxi?",
        "it": "Dove posso prendere un taxi ufficiale?",
        "pron": "도베 포쏘 프렌데레 운 탁시 우피칠레",
        "tip": "💡 로마 공항엔 흰색 공식 택시만 이용! 사설 호객꾼 절대 NO. 'Taxi Ufficiale' 표지 따라가세요."
    },
    {
        "no": 8,
        "category": "✈️ 로마 공항 · 이동",
        "situation": "시내까지 요금 물을 때",
        "short_en": "City center, how much?",
        "short_it": "Centro, quanto?",
        "en": "How much to the city center?",
        "it": "Quanto costa andare in centro?",
        "pron": "콴토 코스타 안다레 인 첸트로",
        "tip": "💡 피우미치노↔로마 시내 공식 고정 요금 €50. 미터기 없이 흥정하려 하면 바가지!"
    },
    {
        "no": 9,
        "category": "✈️ 로마 공항 · 이동",
        "situation": "목적지 주소 알려줄 때",
        "short_en": "[Show phone screen with address]",
        "short_it": "Questo indirizzo, per favore.",
        "en": "Please take me to this address.",
        "it": "Mi porti a questo indirizzo, per favore.",
        "pron": "미 포르티 아 크에스토 인디리쪼, 페르 파보레",
        "tip": "💡 폰 화면에 주소 띄워서 보여주는 게 가장 확실! 발음 걱정 없이 해결돼요."
    },
    {
        "no": 10,
        "category": "🏨 호텔 · 숙소",
        "situation": "호텔 체크인",
        "q": "Do you have a reservation? / Ha una prenotazione?",
        "short_en": "Reservation for [name].",
        "short_it": "Prenotazione a nome [nome].",
        "en": "I have a reservation. My name is [name].",
        "it": "Ho una prenotazione. Mi chiamo [nome].",
        "pron": "오 우나 프레노타지오네. 미 키아모 [이름]",
        "tip": "💡 이탈리아 호텔은 여권 제시 필수! 체크인 시 꼭 지참하세요."
    },
    {
        "no": 11,
        "category": "🏨 호텔 · 숙소",
        "situation": "와이파이 비밀번호 물을 때",
        "short_en": "WiFi password?",
        "short_it": "Password WiFi?",
        "en": "What is the WiFi password?",
        "it": "Qual è la password del WiFi?",
        "pron": "콸 에 라 파스워드 델 와이파이",
        "tip": "💡 이탈리아에선 WiFi를 '왈라이 파이'처럼 발음해요. 'Password WiFi?' 짧게 물어보면 돼요."
    },
    {
        "no": 12,
        "category": "🏨 호텔 · 숙소",
        "situation": "체크아웃 시간 물을 때",
        "short_en": "Check-out time?",
        "short_it": "Orario di check-out?",
        "en": "What time is check-out?",
        "it": "A che ora è il check-out?",
        "pron": "아 케 오라 에 일 체크아웃",
        "tip": "💡 대부분 11시~12시. 짐 맡기려면 'Posso lasciare il bagaglio?'(짐 맡길 수 있나요?)도 함께!"
    },

    # ===== 13-22: 로마 관광 =====
    {
        "no": 13,
        "category": "🏛️ 로마 관광",
        "situation": "입장권 구매처 물을 때",
        "short_en": "Tickets?",
        "short_it": "Biglietti?",
        "en": "Where do I buy tickets?",
        "it": "Dove si comprano i biglietti?",
        "pron": "도베 시 콤프라노 이 빌리에티",
        "tip": "💡 콜로세오·바티칸 등은 온라인 사전 예매 필수! 현장은 대기 2~3시간 기본이에요."
    },
    {
        "no": 14,
        "category": "🏛️ 로마 관광",
        "situation": "대기 시간 확인",
        "short_en": "How long is the wait?",
        "short_it": "Quanto si aspetta?",
        "en": "How long is the wait?",
        "it": "Quanto tempo si aspetta?",
        "pron": "콴토 템포 시 아스페타",
        "tip": "💡 짧게 'Quanto si aspetta?'(콴토 시 아스페타) 한 마디면 OK!"
    },
    {
        "no": 15,
        "category": "🏛️ 로마 관광",
        "situation": "사진 촬영 가능 여부",
        "short_en": "Photos OK?",
        "short_it": "Foto, ok?",
        "en": "Can I take photos here?",
        "it": "Posso fare foto qui?",
        "pron": "포쏘 파레 포토 쿠이",
        "tip": "💡 시스티나 성당 내부는 촬영 금지! 'No foto'라고 쓰여 있어요. 미리 확인하는 습관!"
    },
    {
        "no": 16,
        "category": "🏛️ 로마 관광",
        "situation": "화장실 위치",
        "short_en": "Toilet?",
        "short_it": "Il bagno?",
        "en": "Where is the restroom?",
        "it": "Dov'è il bagno?",
        "pron": "도베 일 반요",
        "tip": "💡 'Il bagno?'(일 반요) 단 세 글자로 해결! 공중화장실은 유료가 많아요(동전 €0.50 준비)."
    },
    {
        "no": 17,
        "category": "🏛️ 로마 관광",
        "situation": "영어 지도/안내서 요청",
        "short_en": "Map in English?",
        "short_it": "Mappa in inglese?",
        "en": "Do you have a map in English?",
        "it": "Ha una mappa in inglese?",
        "pron": "아 우나 마파 인 잉글레제",
        "tip": "💡 대부분 관광지 안내소에서 무료 지도 제공. 'Free map?' 해도 알아들어요."
    },
    {
        "no": 18,
        "category": "🏛️ 로마 관광",
        "situation": "영어 가이드 투어 문의",
        "short_en": "English tour?",
        "short_it": "Tour in inglese?",
        "en": "Is there a guided tour in English?",
        "it": "C'è una visita guidata in inglese?",
        "pron": "체 우나 비지타 귀다타 인 잉글레제",
        "tip": "💡 바티칸·콜로세오는 영어 오디오가이드나 그룹 투어가 풍부해요. 역사를 들으면 두 배로 재밌어요!"
    },
    {
        "no": 19,
        "category": "🏛️ 로마 관광",
        "situation": "도보 이동 거리 확인",
        "short_en": "Walking distance?",
        "short_it": "A piedi, quanto?",
        "en": "Is it walkable from here?",
        "it": "Si può andare a piedi da qui?",
        "pron": "시 푸오 안다레 아 피에디 다 쿠이",
        "tip": "💡 로마 중심부는 트레비·스페인광장·판테온 모두 도보권! 지하철보다 걸어다니는 게 더 재밌어요."
    },
    {
        "no": 20,
        "category": "🏛️ 로마 관광",
        "situation": "식당 추천 요청",
        "short_en": "Good restaurant nearby?",
        "short_it": "Ristorante qui vicino?",
        "en": "Can you recommend a good restaurant nearby?",
        "it": "Può consigliarmi un buon ristorante qui vicino?",
        "pron": "푸오 콘실리아르미 운 부온 리스토란테 쿠이 비치노",
        "tip": "💡 현지인 단골집은 'trattoria'(트라토리아). 관광지 바로 앞보다 골목 안 식당이 훨씬 맛있어요!"
    },
    {
        "no": 21,
        "category": "🏛️ 로마 관광",
        "situation": "지하철로 테르미니역 가는 법",
        "short_en": "Metro to Termini?",
        "short_it": "Metro per Termini?",
        "en": "Which metro line goes to Termini?",
        "it": "Quale linea della metro va a Termini?",
        "pron": "콸레 리네아 델라 메트로 바 아 테르미니",
        "tip": "💡 로마 지하철: A선(오렌지)·B선(파랑) 두 개뿐. 테르미니역에서 환승 가능!"
    },
    {
        "no": 22,
        "category": "🏛️ 로마 관광",
        "situation": "트레비 분수에서 동전 던지기",
        "short_en": "I'll be back!",
        "short_it": "Tornerò!",
        "en": "One coin — I'll return to Rome!",
        "it": "Una moneta — tornerò a Roma!",
        "pron": "우나 모네타 — 토르네로 아 로마",
        "tip": "💡 오른손으로 왼쪽 어깨 너머로! 1개=재방문, 2개=사랑, 3개=결혼. 'Tornerò!'(돌아올게!)를 외쳐보세요."
    },

    # ===== 23-32: 렌터카 =====
    {
        "no": 23,
        "category": "🚗 렌터카",
        "situation": "예약 확인",
        "short_en": "Reservation for [name].",
        "short_it": "Prenotazione a nome [nome].",
        "en": "I have a car reservation under my name.",
        "it": "Ho una prenotazione per un'auto a mio nome.",
        "pron": "오 우나 프레노타지오네 페르 우나우토 아 미오 노메",
        "tip": "💡 예약 확인서 + 국제운전면허증 + 여권 + 신용카드 4가지 세트 필수!"
    },
    {
        "no": 24,
        "category": "🚗 렌터카",
        "situation": "자동 변속기 요청",
        "short_en": "Automatic, please.",
        "short_it": "Automatico, per favore.",
        "en": "I'd like an automatic transmission, please.",
        "it": "Vorrei un'auto con cambio automatico, per favore.",
        "pron": "보레이 우나우토 콘 캄비오 아우토마티코, 페르 파보레",
        "tip": "💡 이탈리아 렌터카 기본값은 수동(manuale)! 자동(automatico)은 반드시 예약 시 지정해야 해요."
    },
    {
        "no": 25,
        "category": "🚗 렌터카",
        "situation": "완전 보험 가입",
        "short_en": "Full insurance, please.",
        "short_it": "Assicurazione completa.",
        "en": "I'd like full insurance coverage, please.",
        "it": "Vorrei l'assicurazione completa, per favore.",
        "pron": "보레이 라씨쿠라지오네 콤플레타, 페르 파보레",
        "tip": "💡 CDW + Super CDW 풀커버 강력 추천! 이탈리아 운전은 변수가 많아요."
    },
    {
        "no": 26,
        "category": "🚗 렌터카",
        "situation": "차량 반납 장소 확인",
        "short_en": "Car return, where?",
        "short_it": "Dove restituisco l'auto?",
        "en": "Where do I return the car?",
        "it": "Dove devo restituire l'auto?",
        "pron": "도베 데보 레스티투이레 라우토",
        "tip": "💡 편도 반납(one-way)은 추가 요금 발생 가능. 계약 전 반드시 확인!"
    },
    {
        "no": 27,
        "category": "🚗 렌터카",
        "situation": "주유 종류 확인",
        "short_en": "Diesel or petrol?",
        "short_it": "Diesel o benzina?",
        "en": "Is this car diesel or petrol?",
        "it": "Quest'auto è diesel o benzina?",
        "pron": "크에스타우토 에 디에젤 오 벤지나",
        "tip": "💡 verde=보통휘발유, super=고급휘발유, gasolio=경유. 주유 전 반드시 확인! 잘못 넣으면 엔진 손상."
    },
    {
        "no": 28,
        "category": "🚗 렌터카 · 주의",
        "situation": "ZTL 구역 진입 전 확인",
        "short_en": "ZTL zone here?",
        "short_it": "ZTL qui?",
        "en": "Is this a ZTL restricted traffic zone?",
        "it": "Questa è una zona ZTL?",
        "pron": "크에스타 에 우나 조나 제타 티 엘레",
        "tip": "💡 ZTL 무단진입 시 €100~500 벌금! 피렌체·시에나 구시가지 특히 주의. 내비에 ZTL 설정 ON!"
    },
    {
        "no": 29,
        "category": "🚗 렌터카 · 주의",
        "situation": "속도 제한 확인",
        "short_en": "Speed limit?",
        "short_it": "Limite di velocità?",
        "en": "What is the speed limit here?",
        "it": "Qual è il limite di velocità qui?",
        "pron": "콸 에 일 리미테 디 벨로치타 쿠이",
        "tip": "💡 시내 50km/h · 국도 90km/h · 고속도로 130km/h. 이탈리아 단속 카메라 매우 많아요!"
    },
    {
        "no": 30,
        "category": "🚗 렌터카 · 긴급",
        "situation": "타이어 펑크",
        "short_en": "Flat tire!",
        "short_it": "Gomma a terra!",
        "en": "I have a flat tire. Can you help?",
        "it": "Ho una gomma a terra. Può aiutarmi?",
        "pron": "오 우나 고마 아 테라. 푸오 아이우타르미",
        "tip": "💡 렌터카 계약서에 긴급출동 번호가 있어요. 사진으로 미리 저장! 보통 24시간 무료 지원."
    },
    {
        "no": 31,
        "category": "🚗 렌터카 · 사고",
        "situation": "교통사고 발생",
        "short_en": "Accident! Police!",
        "short_it": "Incidente! Polizia!",
        "en": "I've had an accident. Please call the police.",
        "it": "Ho avuto un incidente. Chiami la polizia, per favore.",
        "pron": "오 아부토 운 인치덴테. 키아미 라 폴리치아, 페르 파보레",
        "tip": "💡 사고 시 긴급번호 112. 유럽 공통 사고신고서(CID 양식) 작성 필수. 렌터카사에도 즉시 연락!"
    },
    {
        "no": 32,
        "category": "🚗 렌터카 · 주차",
        "situation": "주차 가능 여부",
        "short_en": "Park here, OK?",
        "short_it": "Posso parcheggiare?",
        "en": "Can I park here?",
        "it": "Posso parcheggiare qui?",
        "pron": "포쏘 파르케쟈레 쿠이",
        "tip": "💡 파란 줄=유료, 흰 줄=무료, 노란 줄=절대 금지. 파란 줄은 파르코메트로(미터기)에 요금 내야 해요."
    },

    # ===== 33-42: 피렌체 =====
    {
        "no": 33,
        "category": "🌸 피렌체",
        "situation": "우피치 미술관 입장",
        "short_en": "Uffizi, online booking.",
        "short_it": "Uffizi, prenotazione online.",
        "en": "I have an online reservation for the Uffizi.",
        "it": "Ho una prenotazione online per gli Uffizi.",
        "pron": "오 우나 프레노타지오네 온라인 페르 리 우피치",
        "tip": "💡 우피치는 성수기에 현장 대기 2~3시간! 온라인 예약(uffizi.it)은 필수 중의 필수."
    },
    {
        "no": 34,
        "category": "🌸 피렌체",
        "situation": "두오모 쿠폴라 올라가기",
        "short_en": "Dome climb?",
        "short_it": "Salire la cupola?",
        "en": "I'd like to climb the Duomo dome.",
        "it": "Vorrei salire sulla cupola del Duomo.",
        "pron": "보레이 살리레 술라 쿠폴라 델 두오모",
        "tip": "💡 계단 463개, 엘리베이터 없음! 체력 준비 필수. 정상에서 바라보는 피렌체 뷰는 최고!"
    },
    {
        "no": 35,
        "category": "🌸 피렌체",
        "situation": "피렌체 스테이크 주문",
        "short_en": "Bistecca, for two!",
        "short_it": "Bistecca per due!",
        "en": "Bistecca alla Fiorentina for two, please.",
        "it": "Una bistecca alla Fiorentina per due, per favore.",
        "pron": "우나 비스테카 알라 피오렌티나 페르 두에, 페르 파보레",
        "tip": "💡 최소 1kg 이상! 2인이 나눠 먹어요. al sangue(레어)가 정통. 웰던 요청하면 셰프가 서운해해요😄"
    },
    {
        "no": 36,
        "category": "🌸 피렌체",
        "situation": "젤라토 맛집 추천",
        "short_en": "Best gelato?",
        "short_it": "Il miglior gelato?",
        "en": "Where is the best gelato in Florence?",
        "it": "Dov'è il miglior gelato di Firenze?",
        "pron": "도베 일 밀리오르 젤라토 디 피렌체",
        "tip": "💡 색이 선명하게 쌓인 젤라토 = 색소 가득. 뚜껑 달린 금속통 보관 = 진짜 장인 젤라토!"
    },
    {
        "no": 37,
        "category": "🌸 피렌체",
        "situation": "가죽 제품 진품 확인",
        "short_en": "Real leather?",
        "short_it": "Vera pelle?",
        "en": "Is this genuine leather?",
        "it": "È vera pelle?",
        "pron": "에 베라 펠레",
        "tip": "💡 진품엔 'vera pelle' 태그! 산 로렌초 시장보다 가죽학교(Scuola del Cuoio) 근처 상점이 믿을 만해요."
    },
    {
        "no": 38,
        "category": "🌸 피렌체",
        "situation": "짐 맡기기",
        "short_en": "Luggage storage?",
        "short_it": "Deposito bagagli?",
        "en": "Can I store my luggage here?",
        "it": "Posso lasciare il bagaglio qui?",
        "pron": "포쏘 라샤레 일 바갈리오 쿠이",
        "tip": "💡 'deposito bagagli'(데포지토 바갈리) 한 단어만 알아도 어디서든 통해요!"
    },
    {
        "no": 39,
        "category": "🌸 피렌체",
        "situation": "토스카나 와인 추천",
        "short_en": "Local wine?",
        "short_it": "Vino locale?",
        "en": "Can you recommend a local Tuscan wine?",
        "it": "Può consigliarmi un vino toscano locale?",
        "pron": "푸오 콘실리아르미 운 비노 토스카노 로칼레",
        "tip": "💡 피렌체 대표 와인: Chianti Classico(끼안티), Brunello di Montalcino(브루넬로). 하우스 와인도 훌륭해요!"
    },
    {
        "no": 40,
        "category": "🌸 피렌체",
        "situation": "베키오 다리 확인",
        "short_en": "Ponte Vecchio?",
        "short_it": "Ponte Vecchio, dov'è?",
        "en": "Is this the way to Ponte Vecchio?",
        "it": "È questa la strada per Ponte Vecchio?",
        "pron": "에 크에스타 라 스트라다 페르 폰테 베키오",
        "tip": "💡 다리 위 금은방(gioielleria)에서 쇼핑하다 보면 시간 훌쩍 가요. 일몰 때 강이 황금빛으로!"
    },
    {
        "no": 41,
        "category": "🌸 피렌체",
        "situation": "베네치아행 기차 티켓",
        "short_en": "Venice, one ticket.",
        "short_it": "Venezia, un biglietto.",
        "en": "One ticket to Venice, please.",
        "it": "Un biglietto per Venezia, per favore.",
        "pron": "운 빌리에토 페르 베네치아, 페르 파보레",
        "tip": "💡 피렌체↔베네치아 Frecciarossa 약 2시간. 사전 예약이 훨씬 저렴해요(trenitalia.com)."
    },
    {
        "no": 42,
        "category": "🌸 피렌체",
        "situation": "시에나 가는 버스",
        "short_en": "Bus to Siena?",
        "short_it": "Autobus per Siena?",
        "en": "Is there a bus to Siena from here?",
        "it": "C'è un autobus per Siena da qui?",
        "pron": "체 운 아우토부스 페르 시에나 다 쿠이",
        "tip": "💡 피렌체↔시에나 버스 약 1시간 15분. 기차보다 버스가 더 빠르고 저렴한 드문 경우!"
    },

    # ===== 43-52: 베네치아 =====
    {
        "no": 43,
        "category": "🚢 베네치아",
        "situation": "수상버스 1일권 구매",
        "short_en": "Day pass, vaporetto.",
        "short_it": "Abbonamento giornaliero.",
        "en": "A vaporetto day pass, please.",
        "it": "Un abbonamento giornaliero per il vaporetto, per favore.",
        "pron": "운 아보나멘토 죠르날리에로 페르 일 바포레토, 페르 파보레",
        "tip": "💡 2번 이상 탈 거면 1일권이 이득! 1회권 €9.5 vs 1일권 €25."
    },
    {
        "no": 44,
        "category": "🚢 베네치아",
        "situation": "산 마르코 가는 노선",
        "short_en": "San Marco, which line?",
        "short_it": "San Marco, quale linea?",
        "en": "Which vaporetto line goes to St. Mark's Square?",
        "it": "Quale linea del vaporetto va a Piazza San Marco?",
        "pron": "콸레 리네아 델 바포레토 바 아 피아차 산 마르코",
        "tip": "💡 1번 라인 타면 대운하 경치 보면서 산 마르코까지! 느리지만 뷰는 최고예요."
    },
    {
        "no": 45,
        "category": "🚢 베네치아",
        "situation": "곤돌라 요금 확인",
        "short_en": "Gondola, how much?",
        "short_it": "Gondola, quanto?",
        "en": "How much for a gondola ride?",
        "it": "Quanto costa una gita in gondola?",
        "pron": "콴토 코스타 우나 지타 인 곤돌라",
        "tip": "💡 공식 요금 낮 €80~/30분, 밤 €100~/30분. 흥정 불가! 경로·시간은 미리 합의하세요."
    },
    {
        "no": 46,
        "category": "🚢 베네치아",
        "situation": "공항 가는 수상택시",
        "short_en": "Water taxi, airport.",
        "short_it": "Taxi acqueo, aeroporto.",
        "en": "I need a water taxi to the airport.",
        "it": "Ho bisogno di un taxi acqueo per l'aeroporto.",
        "pron": "오 비조뇨 디 운 탁시 아크웨오 페르 라에로포르토",
        "tip": "💡 수상택시는 €100~150로 비싸지만 짐 많을 때 최고. 공공 보트(5번)는 €15로 저렴해요."
    },
    {
        "no": 47,
        "category": "🚢 베네치아",
        "situation": "무라노 유리 진품 확인",
        "short_en": "Real Murano?",
        "short_it": "Murano autentico?",
        "en": "Is this authentic Murano glass?",
        "it": "È vetro di Murano autentico?",
        "pron": "에 베트로 디 무라노 아우텐티코",
        "tip": "💡 진품엔 'Vetro Murano Artistico' 인증 마크! 무라노 섬에서 직접 사면 더 확실해요."
    },
    {
        "no": 48,
        "category": "🚢 베네치아",
        "situation": "아쿠아 알타(홍수) 확인",
        "short_en": "Acqua alta today?",
        "short_it": "C'è acqua alta?",
        "en": "Is there acqua alta today?",
        "it": "C'è acqua alta oggi?",
        "pron": "체 아크와 알타 오지",
        "tip": "💡 베네치아 홍수 정보는 'Città di Venezia' 앱으로! 방수 장화 대여도 가능해요."
    },
    {
        "no": 49,
        "category": "🚢 베네치아",
        "situation": "부라노 섬 가는 정류장",
        "short_en": "Burano, which stop?",
        "short_it": "Burano, quale fermata?",
        "en": "Which stop for Burano Island?",
        "it": "Quale fermata per l'isola di Burano?",
        "pron": "콸레 페르마타 페르 리졸라 디 부라노",
        "tip": "💡 부라노는 12번 라인으로 약 45분. 형형색색 집들 사진 찍으러 꼭 가보세요!"
    },
    {
        "no": 50,
        "category": "🚢 베네치아",
        "situation": "운하 옆 자리 요청",
        "short_en": "By the canal, please.",
        "short_it": "Vicino al canale.",
        "en": "Can we have a table by the canal?",
        "it": "Possiamo avere un tavolo vicino al canale?",
        "pron": "포씨아모 아베레 운 타볼로 비치노 알 카날레",
        "tip": "💡 'Vicino al canale'(비치노 알 카날레) = 운하 옆. 간단하게 이것만 말해도 알아들어요!"
    },
    {
        "no": 51,
        "category": "🚢 베네치아",
        "situation": "베네치아 전통 마스크 구매",
        "short_en": "Venetian mask?",
        "short_it": "Maschera veneziana?",
        "en": "I'm looking for a traditional Venetian mask.",
        "it": "Cerco una maschera veneziana tradizionale.",
        "pron": "체르코 우나 마스케라 베네치아나 트라디지오날레",
        "tip": "💡 중국산 저가품 주의! 장인이 직접 만든 handmade 마스크를 원하면 'fatto a mano?'(수제품?)라고 확인."
    },
    {
        "no": 52,
        "category": "🚢 베네치아",
        "situation": "밀라노행 고속열차",
        "short_en": "Milan, fast train.",
        "short_it": "Milano, Frecciarossa.",
        "en": "One high-speed train to Milan, please.",
        "it": "Un Frecciarossa per Milano, per favore.",
        "pron": "운 프레차로사 페르 밀라노, 페르 파보레",
        "tip": "💡 베네치아↔밀라노 Frecciarossa 약 2시간 20분. 'Frecciarossa'(프레차로사) = 빨간 화살 고속열차."
    },

    # ===== 53-62: 밀라노 =====
    {
        "no": 53,
        "category": "🛍️ 밀라노",
        "situation": "두오모 옥상 포함 티켓",
        "short_en": "Two tickets, Duomo + rooftop.",
        "short_it": "Due biglietti, Duomo + terrazze.",
        "en": "Two tickets for the Duomo including the rooftop.",
        "it": "Due biglietti per il Duomo, incluse le terrazze.",
        "pron": "두에 빌리에티 페르 일 두오모, 인클루제 레 테라체",
        "tip": "💡 옥상 테라스에서 맑은 날엔 알프스까지! 계단(무료) vs 엘리베이터(유료) 선택 가능."
    },
    {
        "no": 54,
        "category": "🛍️ 밀라노",
        "situation": "최후의 만찬 예약 확인",
        "short_en": "Last Supper reservation.",
        "short_it": "Prenotazione, Ultima Cena.",
        "en": "I have a reservation for the Last Supper.",
        "it": "Ho una prenotazione per l'Ultima Cena.",
        "pron": "오 우나 프레노타지오네 페르 룰티마 체나",
        "tip": "💡 최후의 만찬은 2~3개월 전 예매 필수! 15분 관람, 시간 엄수. vivaticket.com에서 예약."
    },
    {
        "no": 55,
        "category": "🛍️ 밀라노",
        "situation": "내 사이즈 있는지 확인",
        "short_en": "My size?",
        "short_it": "Nella mia taglia?",
        "en": "Do you have this in my size?",
        "it": "Ce l'avete nella mia taglia?",
        "pron": "체 라베테 넬라 미아 탈리아",
        "tip": "💡 이탈리아 사이즈: 옷은 한국보다 약 2~3 더 큰 숫자, 신발은 한국 사이즈 +35 정도!"
    },
    {
        "no": 56,
        "category": "🛍️ 밀라노",
        "situation": "명품 거리 위치",
        "short_en": "Via Montenapoleone?",
        "short_it": "Via Montenapoleone, dov'è?",
        "en": "Where is Via Montenapoleone?",
        "it": "Dov'è Via Montenapoleone?",
        "pron": "도베 비아 몬테나폴레오네",
        "tip": "💡 몬테나폴레오네 거리 = 밀라노의 청담동. Prada, Gucci, Versace 본점이 모여 있어요."
    },
    {
        "no": 57,
        "category": "🛍️ 밀라노",
        "situation": "그냥 구경만 할 때",
        "short_en": "Just looking.",
        "short_it": "Solo guardando.",
        "en": "I'm just browsing, thank you.",
        "it": "Sto solo guardando, grazie.",
        "pron": "스토 솔로 구아르단도, 그라치에",
        "tip": "💡 이탈리아 점원은 입장하자마자 다가와요. 'Solo guardando'(솔로 과르단도) 한 마디면 편하게 구경 가능!"
    },
    {
        "no": 58,
        "category": "🛍️ 밀라노",
        "situation": "밀라노 리조또 주문",
        "short_en": "Risotto Milanese!",
        "short_it": "Risotto alla Milanese!",
        "en": "Risotto alla Milanese, please.",
        "it": "Un risotto alla Milanese, per favore.",
        "pron": "운 리조토 알라 밀라네제, 페르 파보레",
        "tip": "💡 사프란(zafferano)으로 만든 노란 리조또가 밀라노 정통! ossobuco(오소부코) 곁들이면 완벽."
    },
    {
        "no": 59,
        "category": "🛍️ 밀라노",
        "situation": "아페롤 스프리츠 주문",
        "short_en": "Spritz, please.",
        "short_it": "Un Spritz.",
        "en": "One Aperol Spritz, please.",
        "it": "Un Aperol Spritz, per favore.",
        "pron": "운 아페롤 스프리츠, 페르 파보레",
        "tip": "💡 저녁 6~8시 아페리티보(aperitivo) 타임! 음료 한 잔 시키면 스낵이 무료로 나와요."
    },
    {
        "no": 60,
        "category": "🛍️ 밀라노",
        "situation": "두오모 가는 지하철 노선",
        "short_en": "Duomo, which metro?",
        "short_it": "Duomo, quale metro?",
        "en": "Which metro line goes to the Duomo?",
        "it": "Quale linea della metro va al Duomo?",
        "pron": "콸레 리네아 델라 메트로 바 알 두오모",
        "tip": "💡 밀라노 두오모역은 M1(빨간선)과 M3(노란선)이 교차. 두 노선 모두 Duomo 정차!"
    },
    {
        "no": 61,
        "category": "🛍️ 밀라노",
        "situation": "갤러리아 입장료 확인",
        "short_en": "Free entry?",
        "short_it": "Ingresso gratuito?",
        "en": "Is the Galleria free to enter?",
        "it": "L'ingresso alla Galleria è gratuito?",
        "pron": "린그레쏘 알라 갈레리아 에 그라투이토",
        "tip": "💡 갤러리아 빅토리오 엠마누엘레 2세 = 세계 최초 쇼핑몰, 입장 무료! 황소 모자이크 밟으며 소원 빌기."
    },
    {
        "no": 62,
        "category": "🛍️ 밀라노",
        "situation": "기차역 짐 보관",
        "short_en": "Luggage storage, station?",
        "short_it": "Deposito bagagli, stazione?",
        "en": "Where is the luggage storage at the station?",
        "it": "Dov'è il deposito bagagli alla stazione?",
        "pron": "도베 일 데포지토 바갈리 알라 스타지오네",
        "tip": "💡 밀라노 중앙역 지하에 코인 로커 + 유인 보관소가 있어요. 약 €6~8/6시간."
    },

    # ===== 63-72: 돌로미티 =====
    {
        "no": 63,
        "category": "⛰️ 돌로미티",
        "situation": "초보자 하이킹 코스 추천",
        "short_en": "Easy trail?",
        "short_it": "Sentiero facile?",
        "en": "Can you recommend an easy hiking trail?",
        "it": "Può consigliarmi un sentiero facile?",
        "pron": "푸오 콘실리아르미 운 센티에로 파칠레",
        "tip": "💡 초보 추천: Lago di Braies(브라이에스 호수) 둘레길 약 3km. 트레치메(Tre Cime)는 중급 이상!"
    },
    {
        "no": 64,
        "category": "⛰️ 돌로미티",
        "situation": "산장(리푸조) 체크인",
        "short_en": "Booking here.",
        "short_it": "Ho una prenotazione.",
        "en": "I have a reservation at this rifugio.",
        "it": "Ho una prenotazione a questo rifugio.",
        "pron": "오 우나 프레노타지오네 아 크에스토 리푸조",
        "tip": "💡 돌로미티 산장(rifugio)은 성수기 예약 필수! 보통 저녁 식사 + 아침 식사 포함 옵션이 있어요."
    },
    {
        "no": 65,
        "category": "⛰️ 돌로미티",
        "situation": "케이블카 위치",
        "short_en": "Cable car?",
        "short_it": "La funivia?",
        "en": "Where is the cable car station?",
        "it": "Dov'è la stazione della funivia?",
        "pron": "도베 라 스타지오네 델라 푸니비아",
        "tip": "💡 funivia(푸니비아)=케이블카, seggiovia(세지오비아)=리프트. 코르티나 담페초(Cortina)가 허브!"
    },
    {
        "no": 66,
        "category": "⛰️ 돌로미티",
        "situation": "내일 산 날씨 확인",
        "short_en": "Weather tomorrow?",
        "short_it": "Tempo domani?",
        "en": "What is the weather forecast for the mountain tomorrow?",
        "it": "Quali sono le previsioni del tempo in montagna domani?",
        "pron": "콸리 소노 레 프레비지오니 델 템포 인 몬타냐 도마니",
        "tip": "💡 돌로미티 날씨 앱: Meteotrentino, Mountain Forecast. 오전은 맑고 오후에 폭풍 잦아요!"
    },
    {
        "no": 67,
        "category": "⛰️ 돌로미티",
        "situation": "트레킹 폴 대여",
        "short_en": "Trekking poles, rent?",
        "short_it": "Bastoni da trekking, noleggio?",
        "en": "Can I rent trekking poles here?",
        "it": "Posso noleggiare dei bastoni da trekking qui?",
        "pron": "포쏘 놀레쟈레 데이 바스토니 다 트레킹 쿠이",
        "tip": "💡 트레치메 트레킹 약 10km, 3~4시간. 폴 있으면 무릎 보호에 훨씬 편해요!"
    },
    {
        "no": 68,
        "category": "⛰️ 돌로미티",
        "situation": "산장에서 따뜻한 음식 주문",
        "short_en": "Hot food?",
        "short_it": "Cibo caldo?",
        "en": "Do you serve hot food?",
        "it": "Servite cibo caldo?",
        "pron": "세르비테 치보 칼도",
        "tip": "💡 리푸조 별미: canederli(카네데를리, 빵 경단 수프). 추운 산에서 먹으면 최고의 한 그릇!"
    },
    {
        "no": 69,
        "category": "⛰️ 돌로미티",
        "situation": "경치에 감탄할 때",
        "short_en": "Amazing!",
        "short_it": "Mozzafiato! / Che bello!",
        "en": "The view is absolutely breathtaking!",
        "it": "Il panorama è assolutamente mozzafiato!",
        "pron": "일 파노라마 에 아쏠루타멘테 모짜피아토",
        "tip": "💡 'Mozzafiato!'(모짜피아토) = 숨 막힐 듯 아름다운. 유네스코 세계유산 돌로미티 앞에서 꼭 써보세요!"
    },
    {
        "no": 70,
        "category": "⛰️ 돌로미티 · 긴급",
        "situation": "산악 구조 요청",
        "short_en": "Emergency! Mountain rescue!",
        "short_it": "Soccorso alpino! Emergenza!",
        "en": "I need mountain rescue! Someone is injured.",
        "it": "Ho bisogno del soccorso alpino! Qualcuno è ferito.",
        "pron": "오 비조뇨 델 소코르소 알피노! 콸쿠노 에 페리토",
        "tip": "💡 산악구조 전화: 118(응급) / 112(유럽 공통). 정확한 GPS 위치를 함께 알려주세요!"
    },
    {
        "no": 71,
        "category": "⛰️ 돌로미티",
        "situation": "트레치메 가는 방법",
        "short_en": "Tre Cime, how to get there?",
        "short_it": "Tre Cime, come si arriva?",
        "en": "How do I get to Tre Cime di Lavaredo?",
        "it": "Come arrivo alle Tre Cime di Lavaredo?",
        "pron": "코메 아리보 알레 트레 치메 디 라베레도",
        "tip": "💡 차로 Rifugio Auronzo(해발 2,320m)까지 올라간 후 트레킹 시작. 주차 약 €25~30."
    },
    {
        "no": 72,
        "category": "⛰️ 돌로미티",
        "situation": "렌터카 반납",
        "short_en": "Car return here.",
        "short_it": "Restituisco l'auto qui.",
        "en": "I'm returning the car here.",
        "it": "Restituisco l'auto qui.",
        "pron": "레스티투이스코 라우토 쿠이",
        "tip": "💡 돌로미티→시칠리아는 비행기가 최선! 볼차노(Bolzano)나 베네치아 공항에서 팔레르모 직항 탑승."
    },

    # ===== 73-92: 시칠리아 =====
    {
        "no": 73,
        "category": "🍋 시칠리아",
        "situation": "팔레르모 공항에서 시내로",
        "short_en": "City center, please.",
        "short_it": "In centro, per favore.",
        "en": "To the city center, please.",
        "it": "Al centro città, per favore.",
        "pron": "알 첸트로 치타, 페르 파보레",
        "tip": "💡 팔레르모 공항↔시내: Prestia e Comandè 버스 €6.30(약 45분) 또는 택시 €35~45."
    },
    {
        "no": 74,
        "category": "🍋 시칠리아",
        "situation": "시칠리아 전통 요리 추천",
        "short_en": "Local dish?",
        "short_it": "Piatto tipico?",
        "en": "What is the typical Sicilian dish here?",
        "it": "Qual è il piatto tipico siciliano qui?",
        "pron": "콸 에 일 피아토 티피코 시칠리아노 쿠이",
        "tip": "💡 시칠리아 3대 음식: arancini(라이스볼), caponata(채소 요리), pasta alla Norma(가지 파스타)!"
    },
    {
        "no": 75,
        "category": "🍋 시칠리아",
        "situation": "아란치니 주문",
        "short_en": "Two arancini!",
        "short_it": "Due arancini!",
        "en": "Two arancini with meat sauce, please.",
        "it": "Due arancini al ragù, per favore.",
        "pron": "두에 아란치니 알 라구, 페르 파보레",
        "tip": "💡 서쪽(팔레르모)=공 모양, 동쪽(카타니아)=원뿔 모양! 같은 음식도 지역마다 달라요."
    },
    {
        "no": 76,
        "category": "🍋 시칠리아",
        "situation": "카놀리 주문",
        "short_en": "Fresh cannoli!",
        "short_it": "Cannoli freschi!",
        "en": "Fresh cannoli filled right now, please.",
        "it": "Cannoli riempiti al momento, per favore.",
        "pron": "카놀리 리엠피티 알 모멘토, 페르 파보레",
        "tip": "💡 'al momento'(지금 채워서)가 핵심! 미리 채워둔 카놀리는 눅눅해요. 신선함이 생명."
    },
    {
        "no": 77,
        "category": "🍋 시칠리아",
        "situation": "오늘의 신선한 해산물",
        "short_en": "Fresh fish today?",
        "short_it": "Pescato del giorno?",
        "en": "What is today's fresh catch?",
        "it": "Qual è il pescato fresco di oggi?",
        "pron": "콸 에 일 페스카토 프레스코 디 오지",
        "tip": "💡 시칠리아 해산물의 보고! 참치(tonno), 황새치(pesce spada), 성게(ricci di mare)가 특히 유명!"
    },
    {
        "no": 78,
        "category": "🍋 시칠리아",
        "situation": "에트나 화산 투어 예약",
        "short_en": "Etna tour, please.",
        "short_it": "Tour dell'Etna.",
        "en": "I'd like to book an Etna volcano tour.",
        "it": "Vorrei prenotare un tour dell'Etna.",
        "pron": "보레이 프레노타레 운 투르 델레트나",
        "tip": "💡 에트나 정상(3,326m)은 가이드 필수, 장비 필요. 2,000m대는 일반 운동화로 가능!"
    },
    {
        "no": 79,
        "category": "🍋 시칠리아",
        "situation": "타오르미나 그리스 극장",
        "short_en": "Greek Theater, Taormina?",
        "short_it": "Teatro Greco di Taormina?",
        "en": "Where is the Greek Theater in Taormina?",
        "it": "Dov'è il Teatro Greco di Taormina?",
        "pron": "도베 일 테아트로 그레코 디 타오르미나",
        "tip": "💡 타오르미나 그리스 극장에서 에트나 화산 + 이오니아 해를 동시에! 시칠리아 최고의 뷰포인트."
    },
    {
        "no": 80,
        "category": "🍋 시칠리아",
        "situation": "해변 선베드 요금",
        "short_en": "Sunbed + umbrella, how much?",
        "short_it": "Lettino + ombrellone, quanto?",
        "en": "How much for a sunbed and umbrella?",
        "it": "Quanto costano un lettino e un ombrellone?",
        "pron": "콴토 코스타노 운 레티노 에 운 옴브렐로네",
        "tip": "💡 유료 해변 €10~25. 무료 해변(spiaggia libera)도 많아요! 표지판 확인 필수."
    },
    {
        "no": 81,
        "category": "🍋 시칠리아",
        "situation": "현지 아침 시장 위치",
        "short_en": "Morning market?",
        "short_it": "Mercato mattutino?",
        "en": "Where is the morning market?",
        "it": "Dov'è il mercato mattutino?",
        "pron": "도베 일 메르카토 마투티노",
        "tip": "💡 팔레르모 발라로 시장(Mercato di Ballarò) = 시칠리아 최대 노천 시장. 오전 일찍 가야 신선!"
    },
    {
        "no": 82,
        "category": "🍋 시칠리아",
        "situation": "아그리젠토 신전 계곡 입장",
        "short_en": "Two tickets, Valley of Temples.",
        "short_it": "Due biglietti, Valle dei Templi.",
        "en": "Two tickets for the Valley of Temples, please.",
        "it": "Due biglietti per la Valle dei Templi, per favore.",
        "pron": "두에 빌리에티 페르 라 발레 데이 템플리, 페르 파보레",
        "tip": "💡 일몰 시간대에 가면 황금빛 신전이 황홀해요. 야간 투어도 있어요!"
    },
    {
        "no": 83,
        "category": "🍋 시칠리아",
        "situation": "팔레르모↔나폴리 페리",
        "short_en": "Ferry to Naples.",
        "short_it": "Traghetto per Napoli.",
        "en": "I'd like a ferry ticket from Palermo to Naples.",
        "it": "Vorrei un biglietto del traghetto da Palermo a Napoli.",
        "pron": "보레이 운 빌리에토 델 트라게토 다 팔레르모 아 나폴리",
        "tip": "💡 팔레르모↔나폴리 야간 페리 약 10시간. 배 안 숙박으로 호텔비 절약 가능!"
    },
    {
        "no": 84,
        "category": "🍋 시칠리아",
        "situation": "시칠리아 와인 주문",
        "short_en": "Nero d'Avola, please.",
        "short_it": "Nero d'Avola.",
        "en": "A glass of local Nero d'Avola, please.",
        "it": "Un bicchiere di Nero d'Avola locale, per favore.",
        "pron": "운 비키에레 디 네로 다볼라 로칼레, 페르 파보레",
        "tip": "💡 Nero d'Avola = 시칠리아 대표 레드 와인. 진하고 과실향 풍부. 'locale'(현지산) 꼭 붙여요!"
    },
    {
        "no": 85,
        "category": "🍋 시칠리아",
        "situation": "길을 잃었을 때",
        "short_en": "I'm lost!",
        "short_it": "Mi sono perso!",
        "en": "I'm lost. Can you help me?",
        "it": "Mi sono perso. Può aiutarmi?",
        "pron": "미 소노 페르소. 푸오 아이우타르미",
        "tip": "💡 시칠리아 골목은 미로 같아요. 구글맵 오프라인 다운로드 필수! 현지인은 친절하게 도와줘요."
    },
    {
        "no": 86,
        "category": "🍋 시칠리아",
        "situation": "천천히 말해달라고",
        "short_en": "Slowly, please.",
        "short_it": "Più lentamente.",
        "en": "Can you speak more slowly, please?",
        "it": "Può parlare più lentamente, per favore?",
        "pron": "푸오 파를라레 피우 렌타멘테, 페르 파보레",
        "tip": "💡 시칠리아 사투리는 이탈리아 북부인도 못 알아들을 정도! 천천히 부탁하는 게 당연해요."
    },
    {
        "no": 87,
        "category": "🍋 시칠리아",
        "situation": "무료 해변 확인",
        "short_en": "Free beach?",
        "short_it": "Spiaggia libera?",
        "en": "Is this a free public beach?",
        "it": "È una spiaggia libera qui?",
        "pron": "에 우나 스피아자 리베라 쿠이",
        "tip": "💡 'spiaggia libera'(자유 해변) = 무료 공공 해변. 시칠리아 남쪽 해안에 무료 해변이 많아요!"
    },
    {
        "no": 88,
        "category": "🍋 시칠리아",
        "situation": "로마행 비행기 터미널",
        "short_en": "Rome flight, which terminal?",
        "short_it": "Volo Roma, quale terminal?",
        "en": "Which terminal for the flight to Rome?",
        "it": "Quale terminal per il volo per Roma?",
        "pron": "콸레 테르미날 페르 일 볼로 페르 로마",
        "tip": "💡 팔레르모 팔코네-보르셀리노 공항 → 로마 피우미치노 약 1시간 10분!"
    },
    {
        "no": 89,
        "category": "🍋 시칠리아",
        "situation": "카타니아 생선 시장",
        "short_en": "Fish market?",
        "short_it": "Mercato del pesce?",
        "en": "Where is the fish market in Catania?",
        "it": "Dov'è il mercato del pesce di Catania?",
        "pron": "도베 일 메르카토 델 페셰 디 카타니아",
        "tip": "💡 카타니아 라 페스케리아(La Pescheria) 오전 6~12시만 운영. 활기찬 시장 분위기 꼭 경험!"
    },
    {
        "no": 90,
        "category": "🍋 시칠리아",
        "situation": "기념품 선물 포장 요청",
        "short_en": "It's a gift.",
        "short_it": "È un regalo.",
        "en": "This is a gift. Can you wrap it?",
        "it": "È un regalo. Può incartarlo?",
        "pron": "에 운 레갈로. 푸오 인카르탈로",
        "tip": "💡 시칠리아 인기 기념품: 마요리카 도자기, 피스타치오 제품(브론테산이 최고!), 에트나 화산석."
    },
    {
        "no": 91,
        "category": "🍋 시칠리아",
        "situation": "그라니타 + 브리오슈 주문",
        "short_en": "Granita + brioche!",
        "short_it": "Granita al limone e brioche!",
        "en": "One lemon granita with brioche, please.",
        "it": "Una granita al limone con brioche, per favore.",
        "pron": "우나 그라니타 알 리모네 콘 브리오슈, 페르 파보레",
        "tip": "💡 시칠리아식 아침 = 그라니타 + 브리오슈! 레몬·아몬드·뽕나무(gelso) 맛이 특히 현지 인기."
    },
    {
        "no": 92,
        "category": "🍋 시칠리아",
        "situation": "다이빙 센터 찾기",
        "short_en": "Diving center?",
        "short_it": "Centro diving?",
        "en": "Is there a diving center nearby?",
        "it": "C'è un centro di immersioni qui vicino?",
        "pron": "체 운 첸트로 디 임메르시오니 쿠이 비치노",
        "tip": "💡 시칠리아 바다 = 지중해 최고 수준 투명도. 에올리에(Aeolian) 제도 다이빙이 특히 유명!"
    },

    # ===== 93-112: 식당 · 카페 =====
    {
        "no": 93,
        "category": "🍝 식당",
        "situation": "레스토랑 예약",
        "short_en": "Table for two, 7 PM.",
        "short_it": "Tavolo per due, alle sette.",
        "en": "I'd like to make a reservation for two at 7 PM.",
        "it": "Vorrei prenotare un tavolo per due alle sette di sera.",
        "pron": "보레이 프레노타레 운 타볼로 페르 두에 알레 세테 디 세라",
        "tip": "💡 이탈리아 저녁 식사는 보통 8~9시 시작. 7시는 이른 편이라 예약 없이도 자리 잡기 쉬워요!"
    },
    {
        "no": 94,
        "category": "🍝 식당",
        "situation": "2인 테이블 요청",
        "short_en": "Two, please.",
        "short_it": "Per due.",
        "en": "A table for two, please.",
        "it": "Un tavolo per due, per favore.",
        "pron": "운 타볼로 페르 두에, 페르 파보레",
        "tip": "💡 'Per due'(페르 두에) 두 글자면 OK! 손가락으로 2를 보여줘도 완벽히 통해요."
    },
    {
        "no": 95,
        "category": "🍝 식당",
        "situation": "메뉴판 요청",
        "short_en": "Menu, please.",
        "short_it": "Il menù.",
        "en": "Can I see the menu, please?",
        "it": "Posso vedere il menù, per favore?",
        "pron": "포쏘 베데레 일 메뉴, 페르 파보레",
        "tip": "💡 이탈리아 정식 순서: antipasto(전채) → primo(파스타/리조또) → secondo(메인) → dolce(디저트)"
    },
    {
        "no": 96,
        "category": "🍝 식당",
        "situation": "추천 메뉴",
        "q": "Are you ready to order? / Siete pronti per ordinare?",
        "short_en": "What's good today?",
        "short_it": "Cosa consiglia?",
        "en": "What do you recommend today?",
        "it": "Cosa consiglia oggi?",
        "pron": "코자 콘실리아 오지",
        "tip": "💡 'Cosa consiglia?'(코자 콘실리아) = 뭘 추천하세요? 오늘의 특선(speciale del giorno)을 물어보세요!"
    },
    {
        "no": 97,
        "category": "🍝 식당",
        "situation": "음식 알레르기 알리기",
        "short_en": "Nut allergy! / Shellfish allergy!",
        "short_it": "Allergia alle noci! / Allergia ai crostacei!",
        "en": "I'm allergic to nuts. Does this contain nuts?",
        "it": "Sono allergico alle noci. Questo contiene noci?",
        "pron": "소노 알레르지코 알레 노치. 크에스토 콘티에네 노치",
        "tip": "💡 알레르기는 반드시 미리! 'allergia'(알레르지아) + 음식 이름으로 간단히 전달 가능."
    },
    {
        "no": 98,
        "category": "🍝 식당",
        "situation": "스테이크 굽기 선택",
        "q": "How would you like your steak? / Come vuole la bistecca?",
        "short_en": "Medium rare.",
        "short_it": "Al sangue. / Media cottura.",
        "en": "Medium rare, please.",
        "it": "Al sangue, per favore.",
        "pron": "알 상궤, 페르 파보레",
        "tip": "💡 굽기: al sangue(레어) / media cottura(미디엄) / ben cotto(웰던). 피렌체 스테이크는 al sangue가 정석!"
    },
    {
        "no": 99,
        "category": "🍝 식당",
        "situation": "탄산 없는 물 주문",
        "q": "Still or sparkling? / Naturale o frizzante?",
        "short_en": "Still, please.",
        "short_it": "Naturale.",
        "en": "A bottle of still water, please.",
        "it": "Una bottiglia d'acqua naturale, per favore.",
        "pron": "우나 보틸리아 다크와 나투랄레, 페르 파보레",
        "tip": "💡 'acqua'만 말하면 탄산수 올 수 있어요! naturale(자연수) vs frizzante(탄산수) 꼭 구분하세요."
    },
    {
        "no": 100,
        "category": "🍝 식당",
        "situation": "하우스 와인 주문",
        "short_en": "House red, please.",
        "short_it": "Vino rosso della casa.",
        "en": "A glass of house red wine, please.",
        "it": "Un bicchiere di vino rosso della casa, per favore.",
        "pron": "운 비키에레 디 비노 로쏘 델라 카사, 페르 파보레",
        "tip": "💡 'vino della casa'(하우스 와인)는 저렴하지만 현지 맛이 담겨 있어요. rosso(레드)/bianco(화이트) 선택!"
    },
    {
        "no": 101,
        "category": "☕ 카페",
        "situation": "카푸치노 주문",
        "short_en": "Cappuccino.",
        "short_it": "Un cappuccino.",
        "en": "A cappuccino, please.",
        "it": "Un cappuccino, per favore.",
        "pron": "운 카푸치노, 페르 파보레",
        "tip": "💡 이탈리아에서 카푸치노는 오전 11시 전까지만! 오후에 주문하면 현지인들이 신기하게 봐요."
    },
    {
        "no": 102,
        "category": "☕ 카페",
        "situation": "에스프레소 주문",
        "short_en": "Espresso.",
        "short_it": "Un caffè.",
        "en": "One espresso, please.",
        "it": "Un caffè, per favore.",
        "pron": "운 카페, 페르 파보레",
        "tip": "💡 이탈리아에서 'caffè' = 에스프레소! 바(bar)에서 서서 마시면 앉아서 마실 때보다 저렴해요."
    },
    {
        "no": 103,
        "category": "🍝 식당",
        "situation": "계산서 요청",
        "short_en": "Check, please.",
        "short_it": "Il conto.",
        "en": "The bill, please.",
        "it": "Il conto, per favore.",
        "pron": "일 콘토, 페르 파보레",
        "tip": "💡 이탈리아에서는 계산서를 직접 요청해야 해요! 그냥 기다리면 영원히 안 가져올 수도..😄"
    },
    {
        "no": 104,
        "category": "🍝 식당",
        "situation": "카드 결제 가능 여부",
        "short_en": "Card OK?",
        "short_it": "Carta, ok?",
        "en": "Do you accept credit cards?",
        "it": "Accettate carte di credito?",
        "pron": "아체타테 카르테 디 크레디토",
        "tip": "💡 이탈리아는 현금 선호 문화! 소규모 식당은 카드 불가 많아요. 항상 현금 €20~30 백업으로 준비."
    },
    {
        "no": 105,
        "category": "🍝 식당",
        "situation": "서비스 요금 포함 여부",
        "short_en": "Service included?",
        "short_it": "Servizio incluso?",
        "en": "Is the service charge included?",
        "it": "Il servizio è incluso?",
        "pron": "일 세르비치오 에 인클루조",
        "tip": "💡 이탈리아 외식비: coperto(자릿세)+servizio(서비스료) 추가될 수 있어요. 영수증 꼭 확인!"
    },
    {
        "no": 106,
        "category": "🍝 식당",
        "situation": "남은 음식 포장 요청",
        "short_en": "To go, please.",
        "short_it": "Da portare via.",
        "en": "Can I have the rest to go?",
        "it": "Posso portare il resto via?",
        "pron": "포쏘 포르타레 일 레스토 비아",
        "tip": "💡 'Da portare via'(다 포르타레 비아) = 포장이요. 이탈리아에서도 요청하면 대부분 해줘요!"
    },
    {
        "no": 107,
        "category": "🍝 식당",
        "situation": "맛 칭찬",
        "short_en": "Delicious!",
        "short_it": "Delizioso! / Buonissimo!",
        "en": "This is absolutely delicious!",
        "it": "È assolutamente delizioso!",
        "pron": "에 아쏠루타멘테 델리치오조",
        "tip": "💡 이탈리아인들은 음식 칭찬을 정말 좋아해요! 'Complimenti al cuoco!'(셰프에게 칭찬을!)도 써보세요."
    },
    {
        "no": 108,
        "category": "🍝 식당",
        "situation": "같은 것 한 번 더",
        "short_en": "Same again.",
        "short_it": "Lo stesso.",
        "en": "Same again, please.",
        "it": "Lo stesso ancora, per favore.",
        "pron": "로 스테쏘 안코라, 페르 파보레",
        "tip": "💡 'Lo stesso'(로 스테쏘) = 같은 걸로요. 와인이나 음료를 더 시킬 때 딱!"
    },
    {
        "no": 109,
        "category": "🍝 식당",
        "situation": "오늘의 특선 확인",
        "short_en": "Today's special?",
        "short_it": "Speciale di oggi?",
        "en": "What is today's special?",
        "it": "Qual è lo speciale di oggi?",
        "pron": "콸 에 로 스페치알레 디 오지",
        "tip": "💡 오늘의 특선은 신선한 재료로 만들어 맛도 좋고 가격도 합리적인 경우가 많아요!"
    },
    {
        "no": 110,
        "category": "🍝 식당",
        "situation": "주방 마감 시간",
        "short_en": "Kitchen close time?",
        "short_it": "Cucina, che ora chiude?",
        "en": "What time does the kitchen close?",
        "it": "A che ora chiude la cucina?",
        "pron": "아 케 오라 키우데 라 쿠치나",
        "tip": "💡 이탈리아 식당은 오후 2~7시 브레이크타임(pausa pranzo)이 있는 경우 많아요. 미리 확인!"
    },
    {
        "no": 111,
        "category": "☕ 카페",
        "situation": "차가운 커피 음료",
        "short_en": "Cold coffee?",
        "short_it": "Caffè freddo?",
        "en": "Do you have any cold coffee drinks?",
        "it": "Avete del caffè freddo?",
        "pron": "아베테 델 카페 프레도",
        "tip": "💡 이탈리아엔 아이스 아메리카노 없어요! 'caffè freddo'(차가운 에스프레소) 또는 'granita al caffè'를 시도!"
    },
    {
        "no": 112,
        "category": "☕ 카페",
        "situation": "커피 테이크아웃",
        "short_en": "To go.",
        "short_it": "Da portare via.",
        "en": "To go, please.",
        "it": "Da portare via, per favore.",
        "pron": "다 포르타레 비아, 페르 파보레",
        "tip": "💡 이탈리아 카페는 서서 마시는 문화! 앉으면 '테라스 요금' 추가. 서서 마시면 더 저렴해요."
    },

    # ===== 113-127: 긴급상황 =====
    {
        "no": 113,
        "category": "🚨 긴급상황",
        "situation": "도움 요청",
        "short_en": "Help!",
        "short_it": "Aiuto!",
        "en": "Help! Please help me!",
        "it": "Aiuto! Mi aiuti, per favore!",
        "pron": "아이우토! 미 아이우티, 페르 파보레",
        "tip": "💡 이탈리아 긴급번호: 112(유럽 통합), 113(경찰), 118(구급). 'Aiuto!'(아이우토!) = 살려주세요!"
    },
    {
        "no": 114,
        "category": "🚨 긴급상황",
        "situation": "경찰 신고",
        "short_en": "Call the police!",
        "short_it": "Polizia! / Carabinieri!",
        "en": "Call the police, please!",
        "it": "Chiami la polizia, per favore!",
        "pron": "키아미 라 폴리치아, 페르 파보레",
        "tip": "💡 Polizia(국가경찰 113) / Carabinieri(군경찰 112). 둘 다 유럽 긴급번호 112로 연락 가능!"
    },
    {
        "no": 115,
        "category": "🚨 긴급상황",
        "situation": "구급차 요청",
        "short_en": "Ambulance! Emergency!",
        "short_it": "Ambulanza! Emergenza!",
        "en": "Call an ambulance! This is an emergency!",
        "it": "Chiami un'ambulanza! È un'emergenza!",
        "pron": "키아미 우남불란차! 에 우네메르젠차",
        "tip": "💡 이탈리아 응급 의료: 118 또는 112. 위치(indirizzo)와 상황을 최대한 명확하게 설명하세요!"
    },
    {
        "no": 116,
        "category": "🚨 긴급상황",
        "situation": "지갑 소매치기",
        "short_en": "My wallet was stolen!",
        "short_it": "Portafoglio rubato!",
        "en": "My wallet was stolen. I need to report it.",
        "it": "Mi hanno rubato il portafoglio. Devo fare una denuncia.",
        "pron": "미 안노 루바토 일 포르타폴리오. 데보 파레 우나 데눈차",
        "tip": "💡 소매치기 신고는 경찰서(Questura)에서 denuncia(신고서) 작성. 보험 청구에 꼭 필요해요!"
    },
    {
        "no": 117,
        "category": "🚨 긴급상황",
        "situation": "여권 분실",
        "short_en": "Lost my passport!",
        "short_it": "Passaporto perso!",
        "en": "I lost my passport. Where is the Korean embassy?",
        "it": "Ho perso il passaporto. Dov'è l'ambasciata coreana?",
        "pron": "오 페르소 일 파사포르토. 도베 람바샤타 코레아나",
        "tip": "💡 여권 분실 시: ①경찰 신고(denuncia) ②주이탈리아 한국대사관 +39-06-802461 연락!"
    },
    {
        "no": 118,
        "category": "🚨 긴급상황",
        "situation": "가까운 병원 찾기",
        "short_en": "Hospital?",
        "short_it": "Ospedale?",
        "en": "Where is the nearest hospital?",
        "it": "Dov'è l'ospedale più vicino?",
        "pron": "도베 로스페달레 피우 비치노",
        "tip": "💡 응급실 = 'Pronto Soccorso'(프론토 소코르소). 여행자 보험 꼭 가입! EU 외 여행자는 유료 진료."
    },
    {
        "no": 119,
        "category": "🚨 긴급상황",
        "situation": "약국 찾기",
        "short_en": "Pharmacy?",
        "short_it": "Farmacia?",
        "en": "Where is the nearest pharmacy?",
        "it": "Dov'è la farmacia più vicina?",
        "pron": "도베 라 파르마치아 피우 비치나",
        "tip": "💡 이탈리아 약국 = 초록 십자가(+) 표시. 영업 외엔 'farmacia di turno'(당번 약국) 찾아보세요!"
    },
    {
        "no": 120,
        "category": "🚨 긴급상황",
        "situation": "두통약 구매",
        "short_en": "Headache medicine?",
        "short_it": "Qualcosa per il mal di testa?",
        "en": "Do you have anything for a headache?",
        "it": "Ha qualcosa per il mal di testa?",
        "pron": "아 콸코자 페르 일 말 디 테스타",
        "tip": "💡 처방전 없이 살 수 있는 진통제: Tachipirina(파라세타몰), Moment(이부프로펜)."
    },
    {
        "no": 121,
        "category": "🚨 긴급상황",
        "situation": "배탈 증상",
        "short_en": "Stomachache.",
        "short_it": "Mal di stomaco.",
        "en": "I have a stomachache and feel nauseous.",
        "it": "Ho mal di stomaco e mi sento nauseato.",
        "pron": "오 말 디 스토마코 에 미 센토 나우제아토",
        "tip": "💡 이탈리아 음식이 맞지 않을 때 대비! 소화제(digestivo)와 지사제(antidiarroico) 미리 챙기세요."
    },
    {
        "no": 122,
        "category": "🚨 긴급상황",
        "situation": "알레르기 반응 응급",
        "short_en": "Allergic reaction! Help!",
        "short_it": "Reazione allergica! Aiuto!",
        "en": "I'm having an allergic reaction. I need help now!",
        "it": "Ho una reazione allergica. Ho bisogno di aiuto adesso!",
        "pron": "오 우나 레아치오네 알레르지카. 오 비조뇨 디 아이우토 아데쏘",
        "tip": "💡 심각한 알레르기 반응은 즉시 118! 에피펜 소지자는 약국에서 미리 보여주면 대비 가능해요."
    },
    {
        "no": 123,
        "category": "🚨 긴급상황",
        "situation": "분실물 센터",
        "short_en": "Lost and found?",
        "short_it": "Oggetti smarriti?",
        "en": "Where is the lost and found office?",
        "it": "Dov'è l'ufficio oggetti smarriti?",
        "pron": "도베 루피치오 오제티 스마리티",
        "tip": "💡 'Oggetti smarriti'(분실물 센터)는 기차역, 공항에 있어요. 빨리 신고할수록 찾을 확률 높아요!"
    },
    {
        "no": 124,
        "category": "🚨 긴급상황",
        "situation": "기차 놓쳤을 때",
        "short_en": "I missed my train!",
        "short_it": "Ho perso il treno!",
        "en": "I missed my train. What should I do?",
        "it": "Ho perso il treno. Cosa devo fare?",
        "pron": "오 페르소 일 트레노. 코자 데보 파레",
        "tip": "💡 Trenitalia는 당일 같은 구간 다음 열차 탑승 가능(조건부). 창구 직원에게 바로 문의!"
    },
    {
        "no": 125,
        "category": "🚨 긴급상황",
        "situation": "여행자 보험 번호 제시",
        "short_en": "Here's my insurance number.",
        "short_it": "Ecco il numero assicurazione.",
        "en": "Here is my travel insurance number.",
        "it": "Ecco il mio numero di assicurazione viaggio.",
        "pron": "에꼬 일 미오 누메로 디 아씨쿠라지오네 비아조",
        "tip": "💡 보험사 긴급연락처 + 보험 번호를 스마트폰에 미리 저장해두세요. 사진 찍어두는 것도 좋아요!"
    },
    {
        "no": 126,
        "category": "🚨 긴급상황",
        "situation": "신용카드 분실 신고",
        "short_en": "Card stolen! Cancel it!",
        "short_it": "Carta rubata! Bloccarla!",
        "en": "My credit card was stolen. I need to cancel it.",
        "it": "Mi hanno rubato la carta di credito. Devo bloccarla.",
        "pron": "미 안노 루바토 라 카르타 디 크레디토. 데보 블로카를라",
        "tip": "💡 카드 분실 즉시 카드사 국제 분실 신고! 번호를 폰에 미리 저장해두는 게 최선이에요."
    },
    {
        "no": 127,
        "category": "🚨 긴급상황",
        "situation": "한국 영사관 연락",
        "short_en": "Korean Embassy?",
        "short_it": "Ambasciata Coreana?",
        "en": "I need to contact the Korean Embassy.",
        "it": "Devo contattare l'Ambasciata Coreana.",
        "pron": "데보 콘타타레 람바샤타 코레아나",
        "tip": "💡 주이탈리아 한국대사관(로마): +39-06-802461. 해외 영사 콜센터: +82-2-3210-0404 (24시간)"
    },

    # ===== 128-150: 쇼핑 · 교통 · 기타 =====
    {
        "no": 128,
        "category": "🛒 쇼핑",
        "situation": "가격 묻기",
        "short_en": "How much?",
        "short_it": "Quanto?",
        "en": "How much does this cost?",
        "it": "Quanto costa questo?",
        "pron": "콴토 코스타 크에스토",
        "tip": "💡 'Quanto?'(콴토) 한 마디면 어디서든 통해요! 이탈리아 시장에선 가격 흥정 가능한 경우도 있어요."
    },
    {
        "no": 129,
        "category": "🛒 쇼핑",
        "situation": "너무 비쌀 때",
        "short_en": "Too expensive!",
        "short_it": "Troppo caro!",
        "en": "That's too expensive. Can you do better?",
        "it": "È troppo caro. Può farmi un prezzo migliore?",
        "pron": "에 트로포 카로. 푸오 파르미 운 프레초 밀리오레",
        "tip": "💡 'Troppo caro!'(너무 비싸요!) 한마디만 해도 흥정 시작! 노천 시장에서 여러 개 살 때 효과적."
    },
    {
        "no": 130,
        "category": "🛒 쇼핑",
        "situation": "세금 환급 신청",
        "short_en": "Tax refund?",
        "short_it": "Rimborso IVA?",
        "en": "I'd like a tax refund form, please.",
        "it": "Vorrei il modulo per il rimborso IVA, per favore.",
        "pron": "보레이 일 모둘로 페르 일 림보르소 이바, 페르 파보레",
        "tip": "💡 EU 비거주자는 €155 이상 구매 시 TAX FREE 가능! 공항 출국 전 세관(dogana)에서 도장 받아야 해요."
    },
    {
        "no": 131,
        "category": "🛒 쇼핑",
        "situation": "영수증 요청",
        "short_en": "Receipt, please.",
        "short_it": "La ricevuta.",
        "en": "Can I have a receipt, please?",
        "it": "Posso avere la ricevuta, per favore?",
        "pron": "포쏘 아베레 라 리체부타, 페르 파보레",
        "tip": "💡 이탈리아는 영수증(ricevuta fiscale) 의무 발급! 가게 나올 때까지 소지 의무가 있어요."
    },
    {
        "no": 132,
        "category": "🛒 쇼핑",
        "situation": "다른 색상 있는지",
        "short_en": "Other color?",
        "short_it": "Altro colore?",
        "en": "Do you have this in another color?",
        "it": "Ce l'avete in un altro colore?",
        "pron": "체 라베테 인 운 알트로 콜로레",
        "tip": "💡 색상: rosso(빨강), blu(파랑), verde(초록), nero(검정), bianco(흰색), giallo(노랑)"
    },
    {
        "no": 133,
        "category": "🛒 쇼핑",
        "situation": "입어볼 수 있는지",
        "short_en": "Try on?",
        "short_it": "Posso provarlo?",
        "en": "Can I try this on?",
        "it": "Posso provarlo?",
        "pron": "포쏘 프로발로",
        "tip": "💡 피팅룸 = 'camerino'(카메리노). 이탈리아 사이즈는 한국보다 커요. 한 치수 작게 시도해보세요!"
    },
    {
        "no": 134,
        "category": "🛒 쇼핑",
        "situation": "교환 요청",
        "short_en": "Exchange, please.",
        "short_it": "Cambio, per favore.",
        "en": "I'd like to exchange this. It doesn't fit.",
        "it": "Vorrei cambiarlo. Non mi va bene.",
        "pron": "보레이 캄비알로. 논 미 바 베네",
        "tip": "💡 이탈리아 환불 정책은 가게마다 달라요! 구매 전 영수증 보관하고 환불 가능 여부 확인하세요."
    },
    {
        "no": 135,
        "category": "🚇 교통",
        "situation": "버스 정류장 위치",
        "short_en": "Bus stop?",
        "short_it": "Fermata bus?",
        "en": "Where is the nearest bus stop?",
        "it": "Dov'è la fermata dell'autobus più vicina?",
        "pron": "도베 라 페르마타 델라우토부스 피우 비치나",
        "tip": "💡 이탈리아 버스는 탑승 전 티켓 구매 후 탑승! 차 안에서 구매 불가한 경우가 많아요."
    },
    {
        "no": 136,
        "category": "🚇 교통",
        "situation": "지하철 노선도 요청",
        "short_en": "Metro map?",
        "short_it": "Mappa metro?",
        "en": "Can I have a metro map?",
        "it": "Può darmi una mappa della metropolitana?",
        "pron": "푸오 다르미 우나 마파 델라 메트로폴리타나",
        "tip": "💡 구글맵 오프라인 지도를 미리 다운로드해두면 데이터 없이도 지하철 탐색 가능!"
    },
    {
        "no": 137,
        "category": "🚇 교통",
        "situation": "기차 플랫폼 확인",
        "short_en": "Florence, which platform?",
        "short_it": "Firenze, quale binario?",
        "en": "Which platform for the train to Florence?",
        "it": "Su quale binario parte il treno per Firenze?",
        "pron": "수 콸레 비나리오 파르테 일 트레노 페르 피렌체",
        "tip": "💡 이탈리아 기차 플랫폼(binario)은 출발 직전 전광판에 표시! 미리 게이트 근처에서 기다려요."
    },
    {
        "no": 138,
        "category": "🚇 교통",
        "situation": "예약석 확인",
        "short_en": "Reserved?",
        "short_it": "Riservato?",
        "en": "Is this seat reserved?",
        "it": "Questo posto è riservato?",
        "pron": "크에스토 포스토 에 리제르바토",
        "tip": "💡 이탈리아 고속열차는 좌석 지정제. 빈자리라도 무조건 내 자리 확인 후 앉으세요!"
    },
    {
        "no": 139,
        "category": "🚲 이동",
        "situation": "자전거 대여",
        "short_en": "Bike rental?",
        "short_it": "Noleggio bici?",
        "en": "I'd like to rent a bicycle for the day.",
        "it": "Vorrei noleggiare una bicicletta per la giornata.",
        "pron": "보레이 놀레쟈레 우나 비칠레타 페르 라 죠르나타",
        "tip": "💡 피렌체, 볼로냐, 밀라노는 자전거 천국! 공유 자전거 앱(BikeMi, RideMovi)도 편리해요."
    },
    {
        "no": 140,
        "category": "💬 기초 회화",
        "situation": "이탈리아어 공부 중이라고",
        "short_en": "I'm learning Italian!",
        "short_it": "Sto imparando l'italiano!",
        "en": "I'm learning Italian. Please be patient with me.",
        "it": "Sto imparando l'italiano. Abbia pazienza con me.",
        "pron": "스토 임파란도 리탈리아노. 아비아 파치엔차 콘 메",
        "tip": "💡 이탈리아인들은 외국인이 이탈리아어를 시도하면 정말 좋아하고 격려해줘요!"
    },
    {
        "no": 141,
        "category": "💬 기초 회화",
        "situation": "영어 가능한지 확인",
        "short_en": "English?",
        "short_it": "Inglese?",
        "en": "Do you speak English?",
        "it": "Parla inglese?",
        "pron": "파를라 잉글레제",
        "tip": "💡 관광지에서는 영어가 잘 통하지만, 소도시나 현지 식당에선 이탈리아어가 필요할 수 있어요."
    },
    {
        "no": 142,
        "category": "💬 기초 회화",
        "situation": "다시 말해달라고",
        "short_en": "Again, please.",
        "short_it": "Ripeta.",
        "en": "Can you repeat that, please?",
        "it": "Può ripetere, per favore?",
        "pron": "푸오 리페테레, 페르 파보레",
        "tip": "💡 'Ripeta'(리페타) 한 마디로 OK! 이탈리아어는 발음이 규칙적이라 천천히 들으면 점점 이해돼요."
    },
    {
        "no": 143,
        "category": "💬 기초 회화",
        "situation": "이해 못했을 때",
        "short_en": "Write it down?",
        "short_it": "Può scriverlo?",
        "en": "I don't understand. Can you write it down?",
        "it": "Non capisco. Può scriverlo?",
        "pron": "논 카피스코. 푸오 스크리베를로",
        "tip": "💡 말로 안 되면 적어달라고! 또는 폰 번역 앱(구글 번역, DeepL)을 보여주는 것도 훌륭한 방법."
    },
    {
        "no": 144,
        "category": "💬 기초 회화",
        "situation": "인사 (아침/낮)",
        "short_en": "Morning! / Hello!",
        "short_it": "Buongiorno!",
        "en": "Good morning! / Good day!",
        "it": "Buongiorno!",
        "pron": "부온조르노",
        "tip": "💡 'Buongiorno'는 아침~오후 5시까지. 이후엔 'Buonasera'(부오나세라)! 상점 입장 시 항상 인사 먼저."
    },
    {
        "no": 145,
        "category": "💬 기초 회화",
        "situation": "감사 표현",
        "short_en": "Thanks!",
        "short_it": "Grazie!",
        "en": "Thank you very much!",
        "it": "Grazie mille!",
        "pron": "그라치에 밀레",
        "tip": "💡 'Grazie mille!'(천 번의 감사!) 대답은 'Prego'(프레고) = 천만에요. 매일 쓰는 표현!"
    },
    {
        "no": 146,
        "category": "💬 기초 회화",
        "situation": "실례합니다 / 죄송합니다",
        "short_en": "Excuse me! / Sorry!",
        "short_it": "Scusi! / Mi dispiace.",
        "en": "Excuse me. / I'm sorry.",
        "it": "Scusi. / Mi dispiace.",
        "pron": "스쿠지. / 미 디스피아체",
        "tip": "💡 길에서 지나갈 땐 'Permesso!'(페르메쏘). 누군가 부를 땐 'Scusi!' 이 두 개만 알아도 충분!"
    },
    {
        "no": 147,
        "category": "💬 기초 회화",
        "situation": "네 / 아니오",
        "short_en": "Yes. / No. / Maybe.",
        "short_it": "Sì. / No. / Forse.",
        "en": "Yes. / No. / Maybe.",
        "it": "Sì. / No. / Forse.",
        "pron": "씨. / 노. / 포르세.",
        "tip": "💡 이탈리아인은 손짓이 풍부해요! 손가락 흔들기 = No, 엄지 위 = Bene!(좋아요). 눈치껏 읽어보세요."
    },
    {
        "no": 148,
        "category": "💬 기초 회화",
        "situation": "작별 인사",
        "short_en": "Bye! / See you!",
        "short_it": "Ciao! / Arrivederci!",
        "en": "Goodbye! Have a nice day!",
        "it": "Arrivederci! Buona giornata!",
        "pron": "아리베데르치! 부오나 죠르나타",
        "tip": "💡 'Ciao'(챠오)는 친한 사이에서, 'Arrivederci'(아리베데르치)는 정중한 작별 인사예요."
    },
    {
        "no": 149,
        "category": "🇮🇹 여행 마무리",
        "situation": "이탈리아가 최고라고 할 때",
        "short_en": "Italy is the best!",
        "short_it": "L'Italia è bellissima!",
        "en": "Italy is the most beautiful country I've ever visited!",
        "it": "L'Italia è il paese più bello che abbia mai visitato!",
        "pron": "리탈리아 에 일 파에제 피우 벨로 케 아비아 마이 비지타토",
        "tip": "💡 이탈리아인들이 가장 좋아하는 칭찬! 짧게 'Bellissima l'Italia!'만 해도 환하게 웃어줄 거예요."
    },
    {
        "no": 150,
        "category": "🇮🇹 여행 마무리",
        "situation": "다시 오겠다고 할 때",
        "short_en": "I'll be back!",
        "short_it": "Tornerò!",
        "en": "I'll definitely come back to Italy!",
        "it": "Tornerò sicuramente in Italia!",
        "pron": "토르네로 시쿠라멘테 인 이탈리아",
        "tip": "💡 트레비 분수에서 동전 던졌다면 이 표현으로 마무리! Arrivederci, Italia! 🇮🇹"
    },
]
